// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhvblbdcamiynxydmlzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJodmJsYmRjYW1peW54eWRtbHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTY0NjAsImV4cCI6MjA3MDA5MjQ2MH0.pdx_xl-XXDO1pDiCE1n9Ol_K676wFL4wUL5sVn2GJNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});